// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Workshop.Infrastructure.Contracts.Entities
{
    public partial class Service
    {
        [Key]
        public int ServiceId { get; set; }
        public int VehicleId { get; set; }
        [Column(TypeName = "date")]
        public DateTime ServiceDate { get; set; }
        [StringLength(100)]
        public string Description { get; set; }
        [Column(TypeName = "money")]
        public decimal Cost { get; set; }

        [ForeignKey("VehicleId")]
        [InverseProperty("Services")]
        public virtual Vehicle Vehicle { get; set; }
    }
}