// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Workshop.Infrastructure.Contracts.Entities
{
    public partial class Vehicle
    {
        public Vehicle()
        {
            Services = new HashSet<Service>();
        }

        [Key]
        public int VehicleId { get; set; }
        [Required]
        [StringLength(50)]
        public string LicensePlate { get; set; }
        [Required]
        [StringLength(100)]
        public string OwnerName { get; set; }
        [Required]
        [StringLength(50)]
        public string Model { get; set; }
        public int Year { get; set; }

        [InverseProperty("Vehicle")]
        public virtual ICollection<Service> Services { get; set; }
    }
}