// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pokemon.Infrastructure.Contracts.Entities
{
    public partial class PokemonEntity
    {
        public PokemonEntity()
        {
            PokeStatisticsByInitials = new HashSet<PokeStatisticsByInitialEntity>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(100)]
        public string Url { get; set; }

        [InverseProperty("Pokemon")]
        public virtual ICollection<PokeStatisticsByInitialEntity> PokeStatisticsByInitials { get; set; }
    }
}