// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pokemon.Infrastructure.Contracts.Entities
{
    [Table("PokeStatisticsByInitial")]
    public partial class PokeStatisticsByInitialEntity
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Column("initial")]
        [StringLength(1)]
        [Unicode(false)]
        public string Initial { get; set; }
        [Column("counter")]
        public int Counter { get; set; }
        public int PokemonId { get; set; }

        [ForeignKey("PokemonId")]
        [InverseProperty("PokeStatisticsByInitials")]
        public virtual PokemonEntity Pokemon { get; set; }
    }
}