// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OOPBankMultiuser.Infrastructure.Contracts.Entities
{
    public partial class Account
    {
        public Account()
        {
            Movements = new HashSet<Movement>();
        }

        [Key]
        public int IdNumber { get; set; }
        [StringLength(20)]
        public string AccountNumber { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        [StringLength(20)]
        public string Pin { get; set; }
        [StringLength(50)]
        public string Iban { get; set; }
        [Column(TypeName = "money")]
        public decimal Balance { get; set; }

        [InverseProperty("Account")]
        public virtual ICollection<Movement> Movements { get; set; }
    }
}