// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FriendshipManagement.Infrastructure.Contracts.Entities
{
    public partial class Friendship
    {
        public int Id { get; set; }
        public int Friend1Id { get; set; }
        public int Friend2Id { get; set; }
        public int LevelOfFriendship { get; set; }
    }
}