// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FriendshipManagement.Infrastructure.Contracts.Entities
{
    public partial class Pony
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Species { get; set; }
        public string Talent { get; set; }
    }
}