// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SWApiManagement.Infrastructure.Contracts.DBEntities
{
    public partial class Planet
    {
        public Planet()
        {
            Residents = new HashSet<Resident>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public int OrbitalPeriod { get; set; }
        public int RotationPeriod { get; set; }
        [Required]
        [StringLength(50)]
        public string Climate { get; set; }
        public int Population { get; set; }
        [Required]
        [StringLength(50)]
        public string Url { get; set; }

        [InverseProperty("Planet")]
        public virtual ICollection<Resident> Residents { get; set; }
    }
}