// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SWApiManagement.Infrastructure.Contracts.DBEntities
{
    public partial class Resident
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Url { get; set; }
        public int PlanetId { get; set; }

        [ForeignKey("PlanetId")]
        [InverseProperty("Residents")]
        public virtual Planet Planet { get; set; }
    }
}