// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniversitiesManagement.Infrastructure.Contracts.DBEntities
{
    public partial class WebPage
    {
        [Key]
        public int Id { get; set; }
        public int UniversityId { get; set; }
        [Required]
        [StringLength(50)]
        public string WebUrl { get; set; }

        [ForeignKey("UniversityId")]
        [InverseProperty("WebPages")]
        public virtual University University { get; set; }
    }
}