// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Pokemon.Infrastructure.Contracts.Entities;

namespace Pokemon.Infrastructure.Impl.Context
{
    public partial class PokemonApiContext : DbContext
    {
        public PokemonApiContext()
        {
        }

        public PokemonApiContext(DbContextOptions<PokemonApiContext> options)
            : base(options)
        {
        }

        public virtual DbSet<PokeStatisticsByInitialEntity> PokeStatisticsByInitials { get; set; }
        public virtual DbSet<PokemonEntity> Pokemons { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=P-0502\\SQLEXPRESS;Initial Catalog=PokemonApi;Persist Security Info=True;User ID=isa;Password=isa");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PokeStatisticsByInitialEntity>(entity =>
            {
                entity.Property(e => e.Initial).IsFixedLength();

                entity.HasOne(d => d.Pokemon)
                    .WithMany(p => p.PokeStatisticsByInitials)
                    .HasForeignKey(d => d.PokemonId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PokeStatisticsByInitial_Pokemons");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}