// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryManagement.Infrastructure.Contracts.Entities
{
    public partial class Purchase
    {
        [Key]
        public int PurchaseId { get; set; }
        public int BookId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        public int Quantity { get; set; }
        [Column(TypeName = "money")]
        public decimal TotalMoney { get; set; }

        [ForeignKey("BookId")]
        [InverseProperty("Purchases")]
        public virtual Book Book { get; set; }
    }
}