// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using SWApiManagement.Infrastructure.Contracts.DBEntities;

namespace SWApiManagement.Infrastructure.Context
{
    public partial class SWDBPlanetsContext : DbContext
    {
        public SWDBPlanetsContext()
        {
        }

        public SWDBPlanetsContext(DbContextOptions<SWDBPlanetsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Planet> Planets { get; set; }
        public virtual DbSet<Resident> Residents { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=P-0502\\SQLEXPRESS;Initial Catalog=SWDB;Persist Security Info=True;User ID=isa;Password=isa");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Resident>(entity =>
            {
                entity.HasOne(d => d.Planet)
                    .WithMany(p => p.Residents)
                    .HasForeignKey(d => d.PlanetId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Residents_Planets");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}